// admin/src/lib/Header.svelte
<script lang="ts">
  // Header component representing the top bar area
</script>

<header class="top-header">
  <div class="header-left">
    <button class="back-btn">
      <svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
      </svg>
      Back
    </button>
    
    <nav class="breadcrumbs">
      <a href="#home">Home</a>
      <span class="separator">/</span>
      <a href="#events">Events</a>
      <span class="separator">/</span>
      <span class="current">Calendar</span>
    </nav>
  </div>

  <div class="header-right">
    <div class="search-box">
      <svg class="search-icon" width="20" height="20" fill="none" viewBox="0 0 24 24" stroke="#9ca3af" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
      <input type="text" placeholder="Search User, Events and more..." />
    </div>

    <div class="actions">
      <div class="dropdown language-selector">
        <span>English</span>
        <svg width="16" height="16" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
        </svg>
      </div>

      <button class="action-btn" aria-label="Settings">
        <svg width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      </button>

      <button class="action-btn notification-btn" aria-label="Notifications">
        <svg width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
        </svg>
        <span class="badge">1</span>
      </button>

      <div class="user-profile">
        <img src="https://ui-avatars.com/api/?name=Admin&background=dc2626&color=fff" alt="User Profile" />
      </div>
    </div>
  </div>
</header>

<style>
  .top-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 32px;
    background-color: white;
    border-bottom: 1px solid #f1f5f9;
    height: 72px;
    flex-shrink: 0;
  }

  .header-left {
    display: flex;
    align-items: center;
    gap: 24px;
  }

  .back-btn {
    display: flex;
    align-items: center;
    gap: 4px;
    background: transparent;
    border: none;
    color: var(--text-primary);
    font-weight: 600;
    font-size: 14px;
    cursor: pointer;
  }
  .back-btn:hover {
    color: var(--accent);
  }

  .breadcrumbs {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 14px;
    color: var(--text-secondary);
  }

  .breadcrumbs a {
    color: var(--text-secondary);
    text-decoration: none;
    transition: color 0.2s;
  }
  .breadcrumbs a:hover {
    color: var(--accent);
  }

  .breadcrumbs .separator {
    color: var(--text-secondary);
    font-size: 12px;
  }

  .breadcrumbs .current {
    font-weight: 600;
    color: var(--text-primary);
  }

  /* Header Right Area */
  .header-right {
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex: 1; /* Take remaining space */
    margin-left: 48px;
  }

  .search-box {
    position: relative;
    width: 100%;
    max-width: 400px;
    display: flex;
    align-items: center;
  }

  .search-box .search-icon {
    position: absolute;
    left: 14px;
  }

  .search-box input {
    width: 100%;
    padding: 10px 16px 10px 44px;
    border-radius: 20px;
    border: 1px solid var(--border-color);
    background: white;
    font-size: 14px;
  }
  .search-box input:focus {
    outline: none;
    border-color: var(--accent);
    box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.1);
  }

  .actions {
    display: flex;
    align-items: center;
    gap: 24px;
  }

  .language-selector {
    display: flex;
    align-items: center;
    gap: 4px;
    font-size: 14px;
    font-weight: 500;
    cursor: pointer;
    color: var(--text-secondary);
  }
  .language-selector:hover {
    color: var(--text-primary);
  }

  .action-btn {
    background: none;
    border: none;
    cursor: pointer;
    color: var(--text-secondary);
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
  }
  .action-btn:hover {
    color: var(--text-primary);
  }

  .notification-btn .badge {
    position: absolute;
    top: -2px;
    right: -2px;
    background: #f59e0b;
    color: white;
    font-size: 10px;
    font-weight: bold;
    width: 14px;
    height: 14px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .user-profile {
    width: 36px;
    height: 36px;
    border-radius: 50%;
    overflow: hidden;
    cursor: pointer;
    border: 2px solid transparent;
    transition: border-color 0.2s;
  }
  .user-profile:hover {
    border-color: var(--accent);
  }

  .user-profile img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
</style>

// admin/src/components/common/header.tsx
"use client";

import React from "react";
import { Search, Bell, Settings, ChevronLeft, ChevronRight } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { cn } from "@/utils/cn";

export function Header() {
  const router = useRouter();
  const pathname = usePathname();

  return (
    <header className="sticky top-0 z-40 flex h-14 w-full items-center justify-between border-b border-slate-100 bg-white px-8">
      {/* Left side: Back & Breadcrumbs */}
      <div className="flex items-center gap-8">
        <button 
          onClick={() => router.back()}
          className="flex items-center gap-2 text-[13px] font-bold text-slate-800 transition-colors hover:text-orange-500"
        >
          <ChevronLeft size={18} strokeWidth={2.5} />
          <span>Back</span>
        </button>

        <nav className="flex items-center gap-2 text-[12px] font-medium text-slate-400">
          <span className="hover:text-slate-600 cursor-pointer">Finance</span>
          <span className="text-slate-300">/</span>
          <span className="hover:text-slate-600 cursor-pointer">Dashboard</span>
          <span className="text-slate-300">/</span>
          <span className="font-bold text-slate-900 capitalize">
            {pathname === "/" ? "Home" : pathname.split("/").filter(Boolean).join(" / ")}
          </span>
        </nav>
      </div>

      {/* Center: Search Bar matching exactly */}
      <div className="relative w-full max-w-[360px]">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-300" size={16} />
        <input 
          type="text" 
          placeholder="Search User, Events and more.." 
          className="w-full rounded-full border border-slate-100 bg-slate-50/50 py-1.5 pl-11 pr-4 text-[12px] outline-none transition-all focus:bg-white"
        />
      </div>

      {/* Right side: Actions */}
      <div className="flex items-center gap-6">
        <div className="flex items-center gap-1 text-[12px] font-medium text-slate-500 cursor-pointer hover:text-slate-800">
          <span>English</span>
          <ChevronRight size={14} className="rotate-90 text-slate-400" />
        </div>

        <button className="text-slate-400 hover:text-slate-800 transition-colors">
          <Settings size={20} />
        </button>

        <button className="relative text-slate-400 hover:text-slate-800 transition-colors">
          <Bell size={20} />
          <span className="absolute -right-0.5 -top-0.5 flex h-4 w-4 items-center justify-center rounded-full border-2 border-white bg-orange-500 text-[8px] font-bold text-white">
            1
          </span>
        </button>

        <div className="flex h-8 w-8 items-center justify-center rounded-full bg-red-600 text-[11px] font-bold text-white cursor-pointer shadow-sm">
          AD
        </div>
      </div>
    </header>
  );
}
